
# BannedBroadcast by @ItalianDevs4PM

name: BannedBroadcast
description: Broadcast a message when a banned or unwhitelisted player attempts to join
api: [3.0.0-ALPHA7]
version: 1.1.0
main: BannedBroadcast\Main
author: ItalianDevs4PM <NikoZazza, luca28pet, XEmAX32, fycarman, AryToNeX, EvolSoft>
website: https://github.com/ItalianDevs4PM
commands:
  unwl-switch:
    description: Switch unwhitelisted alerts
    usage: "/unwl-switch <on|off>"
    permission: bb.cmd.unwlswitch
  ban-switch:
    description: Switch ban alerts
    usage: "/ban-switch <on|off>"
    permission: bb.cmd.banswitch
permissions:
  bb:
    default: op
    description: "Access to all BannedBroadcast functions"
    children:
      bb.ban:
        default: op
        description: "Broadcast a message when a banned player attempts to join"
      bb.whitelist:
        default: op
        description: "Broadcast a message when a unwhitelisted player attempts to join"
      bb.cmd:
        default: op
        description: "Run all BannedBroadcast commands"
        children:
          bb.cmd.unwlswitch:
            default: op
            description: "Run unwl-switch command"
          bb.cmd.banswitch:
            default: op
            description: "Run ban-switch command"
