
# BannedBroadcast by @ItalianDevs4PM

name: BannedBroadcast
description: Broadcast a message when a banned or unwhitelisted player attempts to join
api: [1.12.0]
version: 1.0.0
main: BannedBroadcast\Main
author: ItalianDevs4PM <xionbig, luca28pet, XEmAX32, fycarman, AryToNex, EvolSoft>
website: https://github.com/ItalianDevs4PM
permissions:
   bb.ban:
     default: op
       description: "Broadcast a message when a banned player attempts to join"
   bb.whitelist:
     default: op
       description: "Broadcast a message when a unwhitelisted player attempts to join"
