name: EchoBananaList
api: [1.12.0]
main: EchoBananaList\Main
author: ItalianDevs4PM <xionbig, luca28pet, XEmAX32,fycarman, AryToNex, EvolSoft>
permissions:
   ebl.ban:
     default: op
       description:
   ebl.whitelist:
     default: op
       description:
