//*Config file for EchoBananaList by ItalianDevs4PM <xionbig, fycarman, luca28pet, XEmAX32, AryToNex, EvolSoft>
You can use {player} for the name of the player and {ip} for the ip of the player.
Here write the message for whitelist join *//
WMessage:
//*Here write the message for ban join *//
BMessage:
