---
# BannedBroadcast v1.0.0 by @ItalianDevs4PM <xionbig, fycarman, luca28pet, XEmAX32, AryToNex, EvolSoft>

# Switch for banned messages
# If "on" the plugin will send messages to players.
banned-switch: true

# Write here the message you want to display when a banned player attempts to join
# Variables: {player} , {ip}
banned-message: "{player} [{ip}] attempted to join but he/she is banned!"

# Switch for unwhitelisted messages
# If "on" the plugin will send messages to players.
unwhitelisted-switch: true

# Write here the message you want to display when a unwhitelisted player attempts to join
# Variables: {player} , {ip]
unwhitelisted-message: "{player} [{ip}] attempted to join but he/she isn't in the whitelist!"

...
